/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/create-event`; params?: Router.UnknownInputParams; } | { pathname: `/create-group`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/events` | `/events`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/groups` | `/groups`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/groups/invite` | `/groups/invite`; params?: Router.UnknownInputParams; } | { pathname: `/group/invite`; params?: Router.UnknownInputParams; } | { pathname: `/event/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/group/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/group/[id]/preferences`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/groups/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/create-event`; params?: Router.UnknownOutputParams; } | { pathname: `/create-group`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/events` | `/events`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/groups` | `/groups`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/groups/invite` | `/groups/invite`; params?: Router.UnknownOutputParams; } | { pathname: `/group/invite`; params?: Router.UnknownOutputParams; } | { pathname: `/event/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/group/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/group/[id]/preferences`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/groups/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/create-event${`?${string}` | `#${string}` | ''}` | `/create-group${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/events${`?${string}` | `#${string}` | ''}` | `/events${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/groups${`?${string}` | `#${string}` | ''}` | `/groups${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/groups/invite${`?${string}` | `#${string}` | ''}` | `/groups/invite${`?${string}` | `#${string}` | ''}` | `/group/invite${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/create-event`; params?: Router.UnknownInputParams; } | { pathname: `/create-group`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/events` | `/events`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/groups` | `/groups`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/groups/invite` | `/groups/invite`; params?: Router.UnknownInputParams; } | { pathname: `/group/invite`; params?: Router.UnknownInputParams; } | `/event/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/group/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/group/${Router.SingleRoutePart<T>}/preferences${`?${string}` | `#${string}` | ''}` | `/groups/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/event/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/group/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/group/[id]/preferences`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/groups/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
